apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: prometheus-injector-webhook
webhooks:
  - name: injector.prometheus-siren.svc
    clientConfig:
      service:
        name: prometheus-injector
        namespace: default
        path: "/mutate"
      caBundle: "" # Injected by cert-manager or manual script
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
